
import { App } from "@slack/bolt";
import { getAnswer } from "./api";
import { v4 as uuidv4 } from "uuid";
require('dotenv').config();

const app = new App({
  token: process.env.SLACKBOT_TOKEN, //Find in the Oauth  & Permissions tab
  signingSecret: process.env.SLACKBOT_SIGNING_SECRET , // Find in Basic Information Tab
  socketMode: true,
  appToken: process.env.SLACKBOT_APP_TOKEN, // Token from the App-level Token that we created
});

interface Conversation {
  channelId: string;
  conversationId?: string, // first time will be generated by server, then save it until reset
  parentId?: string, // parent message id
}
const STATES: {
  instanceId: string;
  token: string;
  convesations: Array<Conversation>;
} = {
  instanceId: uuidv4(),
  token: process.env.CHATGPT_AUTH_TOKEN,
  convesations: []
};

(async () => {
  await app.start();
  console.log(`[INFO] ⚡️ ChatGPT-${STATES.instanceId} Bot App started`);
})();

const handle = async (question: string, say: Function, channel: string) => {
  try {
    let conv = STATES.convesations.find(c => c.channelId === channel);
    if(!conv) {
      conv = {channelId: channel} as Conversation;
      STATES.convesations = STATES.convesations.concat([conv]);
    }
    console.debug(`[DEBUG] ${STATES.instanceId}/#${conv.channelId}.${conv.conversationId} recv question '${question}'`);
    const {answer: result, conversationId, id} = await getAnswer(question, STATES.token, conv.conversationId, conv.parentId);
    conv.conversationId = conversationId;
    conv.parentId = id;
    console.log(`[INFO] chatgpt-${STATES.instanceId}/#${conv.channelId}.${conversationId} Q: '${question}', A: ${result}`);
    say(result);
  } catch (error) {
    console.error(error);
    say(`hatgpt-${STATES.instanceId} error: \`${error.message}\``);
  }
}
app.message(/.*/, async ({context, say, payload, event }) => {
  return handle(context['matches'][0], say, event.channel);
});
app.event("app_mention", async ({context, event, say}) => {
  const q = event.text.replace(`<@${context.botUserId}>`, '');
  return handle(q, say, event.channel);
});
app.command("/chatgpt", async ({ command, ack, say }) => {
  await ack();
  return handle(command.text, say, command.channel_id);
});
app.command("/reset-chatgpt-conversation", async ({ command, ack, say }) => {
  await ack();
  STATES.convesations = STATES.convesations.filter(c => c.channelId !== command.channel_id);
  say(`\`chatgpt-${STATES.instanceId}\` conversation reset done.`);
});
app.command("/print-chatgpt-token", async ({ command, ack, say }) => {
    try {
      await ack();
      say(`\`chatgpt-${STATES.instanceId}\` auth token using : \`${STATES.token || "<not setup>"}\``);
    } catch (error) {
      console.error(error);
      say(`\`chatgpt-${STATES.instanceId}\` auth token get error: ${error.message}`);
    }
});
app.command("/set-chatgpt-token", async ({ command, ack, say }) => {
    try {
      await ack();
      let txt:any = command.text; // The inputted parameters
      STATES.token = txt;
      say(`\`chatgpt-${STATES.instanceId}\` auth setup done, current value as :\`${txt}\``);
    } catch (error) {
      console.error(error);
      say(`\`chatgpt-${STATES.instanceId}\` auth setup fail, error: + \`${error.message}\``);
    }
});